const roomForm = document.getElementById('roomForm'); const roomMessage = document.getElementById('roomMessage');
const request = async (url, method = 'GET', body) => { const response = await fetch(url, body ? { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) } : { method }); const data = await response.json(); if (response.status === 403) { window.location.replace('dashboard.html'); throw new Error('ไม่มีสิทธิ์'); } if (!response.ok) throw new Error(data.error); return data; };
const roomInputs = ['roomId','roomCode','roomBuilding','roomFloor','roomCapacity','roomEquipment'].reduce((items,id)=>({ ...items,[id]:document.getElementById(id)}),{});
function clearRoomForm(){ roomForm.reset(); roomInputs.roomId.value=''; roomInputs.roomBuilding.value='อาคาร IT'; roomForm.hidden=true; roomMessage.textContent=''; }
async function loadRooms(){ try { const data=await request('../api/admin_rooms.php'); document.getElementById('roomsAdminList').innerHTML=data.rooms.length?data.rooms.map(r=>`<div class="manage-row"><div><strong>${r.code}</strong><small>${r.building} ชั้น ${r.floor} · ${r.capacity} คน</small></div><div class="row-actions"><button data-room='${encodeURIComponent(JSON.stringify(r))}' class="edit-room">แก้ไข</button><button data-delete-room='${r.id}' class="danger">ลบ</button></div></div>`).join(''):'<p class="empty-manage">ยังไม่มีห้อง</p>'; }catch(e){document.getElementById('roomsAdminList').innerHTML=`<p class="empty-manage">${e.message}</p>`;} }
async function loadUsers(){ try { const data=await request('../api/admin_users.php'); document.getElementById('usersAdminList').innerHTML=data.users.length?data.users.map(u=>`<div class="manage-row user-row"><div><strong>${u.display_name}</strong><small>@${u.username}</small></div><select data-role-id='${u.id}'><option value="user" ${u.role==='user'?'selected':''}>ผู้ใช้</option><option value="admin" ${u.role==='admin'?'selected':''}>ผู้ดูแล</option></select><div class="row-actions"><button data-save-user='${u.id}' data-name='${encodeURIComponent(u.display_name)}'>บันทึก</button><button data-delete-user='${u.id}' class="danger">ลบ</button></div></div>`).join(''):'<p class="empty-manage">ยังไม่มีผู้ใช้</p>'; }catch(e){document.getElementById('usersAdminList').innerHTML=`<p class="empty-manage">${e.message}</p>`;} }
document.getElementById('newRoom').addEventListener('click',()=>{clearRoomForm();roomForm.hidden=false;}); document.getElementById('cancelRoom').addEventListener('click',clearRoomForm);
roomForm.addEventListener('submit',async e=>{e.preventDefault(); const body={id:Number(roomInputs.roomId.value)||undefined,code:roomInputs.roomCode.value,building:roomInputs.roomBuilding.value,floor:Number(roomInputs.roomFloor.value),capacity:Number(roomInputs.roomCapacity.value),equipment:roomInputs.roomEquipment.value}; try{await request('../api/admin_rooms.php',body.id?'PATCH':'POST',body);clearRoomForm();loadRooms();}catch(err){roomMessage.textContent=err.message;}});
document.getElementById('roomsAdminList').addEventListener('click',async e=>{const edit=e.target.closest('.edit-room');const del=e.target.closest('[data-delete-room]');if(edit){const r=JSON.parse(decodeURIComponent(edit.dataset.room));Object.entries({roomId:r.id,roomCode:r.code,roomBuilding:r.building,roomFloor:r.floor,roomCapacity:r.capacity,roomEquipment:r.equipment}).forEach(([k,v])=>roomInputs[k].value=v);roomForm.hidden=false;roomForm.scrollIntoView({behavior:'smooth'});}if(del&&confirm('ต้องการลบห้องนี้ใช่ไหม?')){try{await request('../api/admin_rooms.php','DELETE',{id:Number(del.dataset.deleteRoom)});loadRooms();}catch(err){alert(err.message);}}});
document.getElementById('usersAdminList').addEventListener('click',async e=>{const save=e.target.closest('[data-save-user]');const del=e.target.closest('[data-delete-user]');if(save){const id=Number(save.dataset.saveUser);try{await request('../api/admin_users.php','PATCH',{id,displayName:decodeURIComponent(save.dataset.name),role:document.querySelector(`[data-role-id="${id}"]`).value});loadUsers();}catch(err){alert(err.message);}}if(del&&confirm('ต้องการลบบัญชีนี้ใช่ไหม?')){try{await request('../api/admin_users.php','DELETE',{id:Number(del.dataset.deleteUser)});loadUsers();}catch(err){alert(err.message);}}});
loadRooms();loadUsers();
